### ISSUE TITLE
GNUC mode compile errors

### ISSUE THREAD

**Issue by csghone** [qyot27/libutvideo#5] opened 2015-01-23 11:06 UTC
In file CPUID.h, in following functions "res" is used instead of "result" for if defined(__GNUC__)
static inline void cpuid 
static inline void xgetbv

**Comment by qyot27** [comment] 2015-01-23 23:07
Fixed in https://github.com/qyot27/libutvideo/commit/161fb016c0cb037ff4f18a18f7a2966b665a2bc1

The issue is that it wasn't adjusted in upstream, likely because upstream dropped GCC support some time ago and this is an artifact of that.

**Closed by qyot27** 2015-01-23 23:07 UTC

**Comment by csghone** [comment] 2015-01-25 15:29
Thanks for the update!
